<a href="https://colab.research.google.com/github/nandivardhan522/PyTorch-Totorial/blob/main/tensor_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [3]:
tensor_1d = torch.arange(0,10)
tensor_1d

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
tensor_1d.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [5]:
tensor_1d.reshape(2,6)

RuntimeError: shape '[2, 6]' is invalid for input of size 10

In [6]:
tensor_1d.reshape(2,-1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [7]:
tensor_2d = tensor_1d.view(2,5)
tensor_2d

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

Difference between Reshape and View

In [8]:
#Updating the values
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [10]:
my_torch5[1]=11
my_torch5

tensor([ 0, 11,  2,  3,  4,  5,  6,  7,  8,  9])

In [11]:
my_torch6

tensor([[ 0, 11,  2,  3,  4],
        [ 5,  6,  7,  8,  9]])

In [12]:
#Slicing
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
#Accesing a specific index value
my_torch7[7]

tensor(7)

In [14]:
my_torch8 = my_torch7.reshape(2,5)
my_torch8

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [15]:
my_torch8[:,1]

tensor([1, 6])

In [16]:
my_torch8[:,1:2]

tensor([[1],
        [6]])