<a href="https://colab.research.google.com/github/nandivardhan522/PyTorch-Totorial/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

LISTS

In [2]:
my_list = [[1,2,3,4,5],[6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

NumPy

In [10]:
import numpy as np
np1 = np.random.rand(3,4)
np1

array([[0.43767605, 0.30813867, 0.90205073, 0.1917263 ],
       [0.66103717, 0.01342107, 0.05045214, 0.04335325],
       [0.54455443, 0.91876649, 0.44616745, 0.27437373]])

In [11]:
np1.dtype

dtype('float64')

TENSORS

In [13]:
import torch
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-0.1927, -1.3992, -0.4773, -0.2667],
        [ 0.5864, -0.5205,  1.1086,  0.7271],
        [ 1.5140,  0.2974,  0.0286,  0.6473]])

In [14]:
tensor_2d.dtype

torch.float32

In [17]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [18]:
tensor_3d.dtype

torch.float32

In [19]:
tensor_np = torch.tensor(np1)
tensor_np

tensor([[0.4377, 0.3081, 0.9021, 0.1917],
        [0.6610, 0.0134, 0.0505, 0.0434],
        [0.5446, 0.9188, 0.4462, 0.2744]], dtype=torch.float64)