<a href="https://colab.research.google.com/github/nandivardhan522/PyTorch-Totorial/blob/main/Tensor_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

Tensor Math operations
*  Add, subtract, multiply, divide, remainder, exponent
*  shorthand and longhand
*  reassignment





In [7]:
tensor_a = torch.arange(1,5)
tensor_b = torch.arange(5,9)

In [8]:
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [9]:
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [10]:
tensor_a-tensor_b

tensor([-4, -4, -4, -4])

In [11]:
torch.subtract(tensor_a,tensor_b)

tensor([-4, -4, -4, -4])

In [12]:
tensor_a*tensor_b

tensor([ 5, 12, 21, 32])

In [13]:
torch.mul(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])

In [15]:
tensor_a//tensor_b

tensor([0, 0, 0, 0])

In [16]:
torch.div(tensor_a,tensor_b)

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [17]:
tensor_a%tensor_b

tensor([1, 2, 3, 4])

In [18]:
torch.remainder(tensor_a,tensor_b)

tensor([1, 2, 3, 4])

In [19]:
tensor_a**tensor_b

tensor([    1,    64,  2187, 65536])

In [20]:
torch.pow(tensor_a,tensor_b)

tensor([    1,    64,  2187, 65536])

In [21]:
tensor_a

tensor([1, 2, 3, 4])

In [22]:
#reassignment
tensor_a += tensor_b

In [23]:
tensor_a

tensor([ 6,  8, 10, 12])